#!/bin/csh -f 
# Sample simulator to Dakota system call script
# See Advanced Simulation Code Interfaces chapter in Users Manual

# $argv[1] is params.in FROM Dakota
# $argv[2] is results.out returned to Dakota

# --------------
# PRE-PROCESSING
# --------------
# Incorporate the parameters from DAKOTA into the template, writing ros.in
# Use the following line if SNL's APREPRO utility is used instead of DPrePro.
# ../aprepro -c '*' -q --nowarning ros.template ros.in

dprepro $argv[1] wing.template wing.in

# --------
# ANALYSIS
# --------
 
run_flapping_fun.sh /mnt/home/train14/MATLAB/MATLAB_Compiler_runtime/v715 wing.in 0 > results.out
# ---------------
# POST-PROCESSING
# ---------------

# extract function value from the simulation output
#grep 'Function value' wing.out | cut -c 18- >! results.tmp
# extract gradients from the simulation output (in this case will be ignored
# by DAKOTA if not needed)
#grep -i 'Function g' wing.out | cut -c 21- >> results.tmp
#mv results.tmp $argv[2]
